import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { initializeSyncEngine } from './syncEngine';
import { setDoc, deleteDoc } from 'firebase/firestore';
import { handleFirestoreError, OperationType } from './firebase';

vi.mock('firebase/firestore', () => ({
  doc: vi.fn(),
  setDoc: vi.fn(),
  deleteDoc: vi.fn(),
  getDocs: vi.fn(),
  collection: vi.fn(),
  onSnapshot: vi.fn(),
}));

vi.mock('firebase/auth', () => ({
  onAuthStateChanged: vi.fn((auth, callback) => {
    // Provide a helper to manually trigger auth state change if needed
    (global as any).triggerAuthState = callback;
  }),
}));

vi.mock('./firebase', () => ({
  db: {},
  auth: { currentUser: { uid: 'test-user-id' } },
  handleFirestoreError: vi.fn(),
  OperationType: { WRITE: 'WRITE', DELETE: 'DELETE', GET: 'GET' },
}));

describe('syncEngine queueCloudPush error handling', () => {
  let consoleErrorSpy: ReturnType<typeof vi.spyOn>;
  let cleanup: () => void;

  beforeEach(() => {
    vi.useFakeTimers();
    consoleErrorSpy = vi.spyOn(console, 'error').mockImplementation(() => {});

    // Clear storage before each test
    localStorage.clear();

    // Setup the listener
    cleanup = initializeSyncEngine(vi.fn());

    // Clear mock calls generated by the initial sweep that setup triggers
    vi.clearAllMocks();
  });

  afterEach(() => {
    cleanup();
    vi.restoreAllMocks();
    vi.useRealTimers();
    localStorage.clear();
  });

  it('should handle setDoc errors in queueCloudPush gracefully', async () => {
    const mockError = new Error('Firestore write failed');
    (setDoc as any).mockRejectedValueOnce(mockError);

    // Trigger queueCloudPush by mocking a storage event
    window.dispatchEvent(new CustomEvent('nexus_storage_changed', {
      detail: { key: 'nexus_testKey', value: 'testValue' }
    }));

    // Fast-forward 300ms debounce
    await vi.runAllTimersAsync();

    expect(consoleErrorSpy).toHaveBeenCalledWith('Error syncing key nexus_testKey to Firestore:', mockError);
    expect(handleFirestoreError).toHaveBeenCalledWith(
      mockError,
      'WRITE',
      'users/test-user-id/localStorageSync/nexus_testKey'
    );
  });

  it('should handle deleteDoc errors in queueCloudPush gracefully', async () => {
    const mockError = new Error('Firestore delete failed');
    (deleteDoc as any).mockRejectedValueOnce(mockError);

    window.dispatchEvent(new CustomEvent('nexus_storage_changed', {
      detail: { key: 'nexus_testKey', value: null }
    }));

    await vi.runAllTimersAsync();

    expect(consoleErrorSpy).toHaveBeenCalledWith('Error syncing key nexus_testKey to Firestore:', mockError);
    expect(handleFirestoreError).toHaveBeenCalledWith(
      mockError,
      'DELETE',
      'users/test-user-id/localStorageSync/nexus_testKey'
    );
  });

  it('should swallow errors thrown by handleFirestoreError', async () => {
    const mockError = new Error('Firestore write failed');
    const nestedError = new Error('Handle error failed');

    (setDoc as any).mockRejectedValueOnce(mockError);
    (handleFirestoreError as any).mockImplementationOnce(() => {
      throw nestedError;
    });

    window.dispatchEvent(new CustomEvent('nexus_storage_changed', {
      detail: { key: 'nexus_testKey', value: 'testValue' }
    }));

    // If it doesn't swallow the error, this will throw and fail the test
    await vi.runAllTimersAsync();

    expect(consoleErrorSpy).toHaveBeenCalledWith('Error syncing key nexus_testKey to Firestore:', mockError);

    // Check that handleFirestoreError was called (at least once for this test scenario)
    expect(handleFirestoreError).toHaveBeenCalled();
  });
});
