# -*- coding: utf-8 -*-
"""
Build the clean WODForge DATA workbook from the raw Resultados_y_RPE export.

Single source of truth: this produces ONLY the `Resultados_y_RPE` data tab,
laid out exactly how WODForge_macros.gs expects it (A1 = "Skip (Libre)",
columns C..Q in the gscript's COLS order). The dashboards are generated by the
gscript (the single calculation engine) — there are no competing openpyxl charts,
so the numbers can never drift between the two.

What this does to the data:
  * Normalizes Kg (kg / bodyweight / decimals).
  * Drops the interleaved section header rows (ACTO I / SEMANA n) so filters work.
  * Seeds the week-4 deload loads (% x 1RM, marked "[plan]") so the taper shows
    once the gscript runs (those rows then have Kg > 0).
  * Flags suspicious RPE/RIR rows with "⚠ Revisar" WITHOUT changing your numbers.

Usage:  python scripts/build_workbook.py [input.csv] [output.xlsx]
"""
import csv, io, re, sys, unicodedata
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

SRC = sys.argv[1] if len(sys.argv) > 1 else "sheet_main.csv"
OUT = sys.argv[2] if len(sys.argv) > 2 else "NEXUS_L4_WODForge_v2.xlsx"

# RM profile (used only to compute the planned deload loads)
PROFILE = {
    "1RM Back Squat (Kg)": 110.0, "1RM Deadlift (Kg)": 140.0,
    "1RM Front Squat (Kg)": 95.0, "1RM Clean & Jerk (Kg)": 85.0,
    "1RM Snatch (Kg)": 65.0, "1RM Thruster (Kg)": 60.0,
    "1RM Strict Press (Kg)": 55.0,
}
EXERCISE_RM = {
    "back squat": "1RM Back Squat (Kg)", "front squat": "1RM Front Squat (Kg)",
    "deadlift": "1RM Deadlift (Kg)", "strict press": "1RM Strict Press (Kg)",
    "snatch": "1RM Snatch (Kg)", "clean": "1RM Clean & Jerk (Kg)",
    "thruster": "1RM Thruster (Kg)",
}

DAY_INDEX = {"lunes": 1, "martes": 2, "miercoles": 3, "jueves": 4,
             "viernes": 5, "sabado": 6, "domingo": 7}
DAY_NAME = {1: "Lunes", 2: "Martes", 3: "Miércoles", 4: "Jueves",
            5: "Viernes", 6: "Sábado", 7: "Domingo"}

strip = lambda s: (s or "").strip()
deacc = lambda s: unicodedata.normalize("NFD", s).encode("ascii", "ignore").decode()

# ------------------------------ parsing ------------------------------------
def bucket_of(bloque):
    """Coarse bucket — only used to decide if a suspicious-RPE flag applies."""
    b = deacc(bloque.lower())
    if re.search(r"fuerza|strength|peak|estabiliz", b): return "Fuerza"
    if re.search(r"metcon|wod|boss|sprint|chipper|team|amrap|emom|couplet|for time|por tiempo", b):
        return "Metcon"
    return "Otro"

def parse_kg(raw):
    """Return a clean Kg string: a number, 'BW' for bodyweight, or '' for blank."""
    v = strip(raw)
    if not v: return ""
    if re.search(r"body\s*weight|^bw$", deacc(v.lower())): return "BW"
    n = v.lower().replace("kg", "").replace(",", ".").strip()
    m = re.match(r"^(\d+(?:\.\d+)?)", n)
    return m.group(1) if m else v

def kg_to_num(clean):
    return float(clean) if re.match(r"^\d+(\.\d+)?$", clean or "") else None

def parse_reps(esquema, ejercicio):
    e = esquema
    desc = re.search(r"\d+(?:\s*-\s*\d+){2,}", e)          # chipper 21-15-9 -> 45
    if desc:
        return sum(int(n) for n in re.findall(r"\d+", desc.group()))
    for rx in [r"(\d+)\s*reps", r"\d+\s*[xX]\s*(\d+)", r"acumular\s*(\d+)"]:
        m = re.search(rx, e, re.I)
        if m: return int(m.group(1))
    m = re.match(r"^\s*(\d+)", ejercicio)
    return int(m.group(1)) if m else None

def parse_intensity(raw):
    v = strip(raw)
    if not v: return None
    pcts = re.findall(r"(\d+(?:\.\d+)?)\s*%", v)
    if pcts: return round(sum(float(x) for x in pcts) / len(pcts), 1)
    m = re.match(r"^\s*(\d*\.\d+|\d+)", v)          # leading fraction "0.5 [..]" -> 50%
    if m:
        n = float(m.group(1))
        if 0 < n <= 1: return round(n * 100, 1)
    return None

def to_num(raw):
    v = strip(raw).replace(",", ".")
    return float(v) if re.match(r"^\d+(\.\d+)?$", v) else None

# ------------------------------ read rows ----------------------------------
rows = list(csv.reader(io.open(SRC, encoding="utf-8")))
header = [strip(h) for h in rows[0]]
IDX = {k: header.index(v) for k, v in {
    "skip": "Skip (Libre)", "fecha": "Fecha Log", "sem": "Semana", "dia": "Día",
    "bloque": "Bloque", "ej": "Ejercicio", "esq": "Esquema Pautado",
    "int": "Intensidad (% RM)", "tempo": "Tempo / Rest", "rondas": "Rondas Completas",
    "repsx": "Reps Extra", "tiempo": "Tiempo Total", "kg": "Kg Levantados",
    "rpe": "RPE", "rir": "RIR", "tipo": "Tipo (Rx/Scaled)",
    "pr": "PR del Mes (Auto)", "notas": "Notas y Comentarios",
}.items()}

records = []
for raw in rows[1:]:
    if len(raw) <= IDX["notas"]:
        raw = raw + [""] * (IDX["notas"] + 1 - len(raw))
    wm = re.match(r"Semana\s*(\d+)", strip(raw[IDX["sem"]]), re.I)
    if not wm:
        continue  # section header / blank row -> dropped
    w = int(wm.group(1))
    di = DAY_INDEX.get(deacc(strip(raw[IDX["dia"]]).lower()))
    if not di:
        continue
    bloque = strip(raw[IDX["bloque"]]); ej = strip(raw[IDX["ej"]])
    if not bloque and not ej:
        continue
    rpe = to_num(raw[IDX["rpe"]]); rir = to_num(raw[IDX["rir"]])
    bucket = bucket_of(bloque)

    flag = ""
    if bucket in ("Fuerza", "Metcon"):
        if rpe is not None and rpe <= 3: flag = "⚠ Revisar"
        elif rir is not None and rir >= 7: flag = "⚠ Revisar"
    if rpe is not None and rir is not None and abs(rpe + rir - 10) > 2:
        flag = "⚠ Revisar"

    records.append({
        "skip": strip(raw[IDX["skip"]]), "fecha": strip(raw[IDX["fecha"]]),
        "sem": f"Semana {w}", "dia": DAY_NAME[di], "bloque": bloque, "ej": ej,
        "esq": strip(raw[IDX["esq"]]), "int": strip(raw[IDX["int"]]).replace("\n", " "),
        "tempo": strip(raw[IDX["tempo"]]), "rondas": strip(raw[IDX["rondas"]]),
        "repsx": strip(raw[IDX["repsx"]]), "tiempo": strip(raw[IDX["tiempo"]]),
        "kg_clean": parse_kg(raw[IDX["kg"]]), "rpe": strip(raw[IDX["rpe"]]),
        "rir": strip(raw[IDX["rir"]]), "tipo": strip(raw[IDX["tipo"]]),
        "pr": strip(raw[IDX["pr"]]), "notas": strip(raw[IDX["notas"]]),
        "w": w, "bucket": bucket, "inten": parse_intensity(raw[IDX["int"]]),
        "reps": parse_reps(strip(raw[IDX["esq"]]), ej), "flag": flag,
    })

# ------ seed planned week-4 deload loads (% x 1RM) so the taper is visible ----
seeded = 0
for rec in records:
    if rec["w"] != 4 or rec["bucket"] != "Fuerza":
        continue
    if kg_to_num(rec["kg_clean"]) is not None or rec["inten"] is None or not rec["reps"]:
        continue
    rm_key = next((k for sub, k in EXERCISE_RM.items() if sub in deacc(rec["ej"].lower())), None)
    if not rm_key:
        continue
    planned = round(rec["inten"] / 100.0 * PROFILE[rm_key], 1)
    if planned <= 0:
        continue
    rec["kg_clean"] = f"{planned:g}"
    rec["notas"] = (rec["notas"] + " · " if rec["notas"] else "") + "[plan: estimado % × 1RM]"
    seeded += 1

# ------------------------------ write tab ----------------------------------
wb = openpyxl.Workbook()
ws = wb.active
ws.title = "Resultados_y_RPE"
ws.sheet_properties.tabColor = "FF007F"

COLS = ["Skip (Libre)", "Fecha Log", "Semana", "Día", "Bloque", "Ejercicio",
        "Esquema Pautado", "Intensidad (% RM)", "Tempo / Rest", "Rondas Completas",
        "Reps Extra", "Tiempo Total", "Kg Levantados", "RPE", "RIR",
        "Tipo (Rx/Scaled)", "PR del Mes (Auto)", "Notas y Comentarios", "⚠ Revisar"]

HDR_FILL = PatternFill("solid", fgColor="1F2A37")
FLAG_FILL = PatternFill("solid", fgColor="7A1F1F")
white_bold = Font(color="FFFFFF", bold=True)
for j, name in enumerate(COLS, 1):
    c = ws.cell(1, j, name)
    c.font = white_bold; c.fill = HDR_FILL
    c.alignment = Alignment(horizontal="center", wrap_text=True)

for i, rec in enumerate(records, start=2):
    vals = [rec["skip"], rec["fecha"], rec["sem"], rec["dia"], rec["bloque"], rec["ej"],
            rec["esq"], rec["int"], rec["tempo"], rec["rondas"], rec["repsx"], rec["tiempo"],
            rec["kg_clean"], rec["rpe"], rec["rir"], rec["tipo"], rec["pr"], rec["notas"],
            rec["flag"]]
    for j, v in enumerate(vals, 1):
        ws.cell(i, j, v)
    if rec["flag"]:
        fc = ws.cell(i, len(COLS))
        fc.fill = FLAG_FILL; fc.font = Font(color="FFD0D0", bold=True)

ws.freeze_panes = "A2"
for col, wdt in {"C": 11, "D": 11, "E": 18, "F": 30, "G": 34, "H": 16, "R": 40, "S": 11}.items():
    ws.column_dimensions[col].width = wdt
ws.auto_filter.ref = f"A1:S{len(records) + 1}"

wb.save(OUT)

flagged = sum(1 for r in records if r["flag"])
print(f"✓ Wrote {OUT}")
print(f"  single tab 'Resultados_y_RPE' · {len(records)} rows · seeded deload: {seeded} · flagged: {flagged}")
print("  A1 =", repr(ws['A1'].value), "(gscript-compatible)")
